/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 26/09/2022 09:01:35
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_CortexFreq_Value                     16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APBFreq_Value                        16000000
#define MX_I2S1Freq_Value                       16000000
#define MX_PWRFreq_Value                        16000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_TIM1Freq_Value                       16000000
#define MX_LPUART1Freq_Value                    16000000
#define MX_LPTIM2Freq_Value                     16000000
#define MX_USART1Freq_Value                     16000000
#define MX_LPTIM1Freq_Value                     16000000
#define MX_ADCFreq_Value                        16000000
#define MX_APBTimFreq_Value                     16000000
#define MX_SYSCLKFreq_VALUE1                    16
#define MX_SYSCLKFreq_VALUE2                    16
#define MX_I2C1Freq_Value                       16000000

/*-------------------------------- SPI1       --------------------------------*/

#define MX_SPI1                                 1

/* GPIO Configuration */

/* Pin PA7 */
#define MX_SPI1_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Pin                        PA7
#define MX_SPI1_MOSI_GPIOx                      GPIOA
#define MX_SPI1_MOSI_PinState                   GPIO_PIN_RESET
#define MX_SPI1_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI1_MOSI_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI1_MOSI_GPIO_AF                    GPIO_AF0_SPI1
#define MX_SPI1_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA1 */
#define MX_SPI1_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Pin                         PA1
#define MX_SPI1_SCK_GPIOx                       GPIOA
#define MX_SPI1_SCK_PinState                    GPIO_PIN_RESET
#define MX_SPI1_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI1_SCK_GPIO_Pin                    GPIO_PIN_1
#define MX_SPI1_SCK_GPIO_AF                     GPIO_AF0_SPI1
#define MX_SPI1_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC SPI1_IRQn */
#define MX_SPI1_IRQn_interruptPremptionPriority 0
#define MX_SPI1_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_SWDIO_Pin                        PA13

/* Pin PA14-BOOT0 */
#define MX_SYS_SWCLK_Pin                        PA14_BOOT0

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PA8 */
#define MX_S_TIM1_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH1_Pin                       PA8
#define MX_S_TIM1_CH1_GPIOx                     GPIOA
#define MX_S_TIM1_CH1_PinState                  GPIO_PIN_RESET
#define MX_S_TIM1_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH1_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM1_CH1_GPIO_AF                   GPIO_AF2_TIM1

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM3_IRQn */
#define MX_TIM3_IRQn_interruptPremptionPriority 0
#define MX_TIM3_IRQn_Subriority                 0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_PinState                   GPIO_PIN_RESET
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF1_USART2

/* Pin PA3 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_PinState                   GPIO_PIN_RESET
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF1_USART2

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 0
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA11 [PA9] */
#define MX_PA11_PA9_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_PA11_PA9_Pin                         PA11_PA9
#define MX_PA11_PA9_GPIOx                       GPIOA
#define MX_PA11_PA9_PinState                    GPIO_PIN_RESET
#define MX_PA11_PA9_GPIO_PuPd                   GPIO_NOPULL
#define MX_PA11_PA9_GPIO_Pin                    GPIO_PIN_11
#define MX_PA11_PA9_GPIO_ModeDefaultOutputPP    GPIO_MODE_OUTPUT_PP

/* Pin PB3 */
#define MX_PB3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB3_Pin                              PB3
#define MX_PB3_GPIOx                            GPIOB
#define MX_PB3_PinState                         GPIO_PIN_RESET
#define MX_PB3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB3_GPIO_Pin                         GPIO_PIN_3
#define MX_PB3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA4 */
#define MX_PA4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_PinState                         GPIO_PIN_RESET
#define MX_PA4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB7 */
#define MX_PB7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB7_Pin                              PB7
#define MX_PB7_GPIOx                            GPIOB
#define MX_PB7_PinState                         GPIO_PIN_RESET
#define MX_PB7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB7_GPIO_Pin                         GPIO_PIN_7
#define MX_PB7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB7_GPIO_FM7                         __NULL

/* Pin PA6 */
#define MX_PA6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_PinState                         GPIO_PIN_RESET
#define MX_PA6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA12 [PA10] */
#define MX_PA12_PA10_Pin                        PA12_PA10
#define MX_PA12_PA10_GPIOx                      GPIOA
#define MX_PA12_PA10_GPIO_PuPd                  GPIO_NOPULL
#define MX_PA12_PA10_GPIO_Pin                   GPIO_PIN_12
#define MX_PA12_PA10_GPIO_Mode                  GPIO_MODE_INPUT

/* Pin PC14-OSC32_IN (PC14) */
#define MX_PC14_OSC32_IN_PC14_GPIO_Speed        GPIO_SPEED_FREQ_LOW
#define MX_PC14_OSC32_IN_PC14_Pin               PC14_OSC32_IN_PC14
#define MX_PC14_OSC32_IN_PC14_GPIOx             GPIOC
#define MX_PC14_OSC32_IN_PC14_PinState          GPIO_PIN_RESET
#define MX_PC14_OSC32_IN_PC14_GPIO_PuPd         GPIO_NOPULL
#define MX_PC14_OSC32_IN_PC14_GPIO_Pin          GPIO_PIN_14
#define MX_PC14_OSC32_IN_PC14_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PA0 */
#define MX_PA0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA0_Pin                              PA0
#define MX_PA0_GPIOx                            GPIOA
#define MX_PA0_PinState                         GPIO_PIN_RESET
#define MX_PA0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA0_GPIO_Pin                         GPIO_PIN_0
#define MX_PA0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

